apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  labels:
    app: webapp
spec:
  ports:
    - port: 8080
# if we were doing this on aws change port to 80/443
#   - port: 80
  selector:
    app: webapp
    tier: frontend
  type: LoadBalancer
---
