apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: webapp
      tier: frontend
  template:
    metadata:
      labels:
        app: webapp
        tier: frontend
    spec:
      containers:
      - image: aterhune1984/webappv2:_9bec13433e153d48e4881cd1da24e3d5836b2919
        name: webapp
        resources:
          requests:
            cpu: 0.2
        env:
        - name: REDIS_HOST
          value: redis-svc
        ports:
        - containerPort: 8080
        command:
          - python
        args:
          - "app.py"
#        volumeMounts:
#        - name: webapp-persistent-storage
#          mountPath: /tmp
#      volumes:
#      - name: webapp-persistent-storage
#        persistentVolumeClaim:
#          claimName: wa-pvc

