apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: webapp
      tier: frontend
  template:
    metadata:
      labels:
        app: webapp
        tier: frontend
    spec:
      containers:
      - image: aterhune1984/webappv2:_948dd10ee518913418b3912a174c7a5e89889a5f
        name: webapp
        resources:
          requests:
            cpu: 0.2
        env:
        - name: REDIS_HOST
          value: redis-svc
        ports:
        - containerPort: 8080
        command:
          - python
        args:
          - "app.py"
        volumeMounts:
        - name: webapp-persistent-storage
          mountPath: /hello
      volumes:
      - name: webapp-persistent-storage
        persistentVolumeClaim:
          claimName: wa-pvc

