apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  labels:
    app: webapp
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: webapp
    tier: frontend
  type: LoadBalancer
---
