apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  labels:
    tier: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: celery
      tier: backend
  template:
    metadata:
      labels:
        app: celery
        tier: backend
    spec:
      containers:
      - image: aterhune1984/webappv2:_8371d5935eb24bb7d9b50e171b5bb2833bb2332d
        name: celery
        resources:
          requests:
            cpu: 0.2
        env:
        - name: REDIS_HOST
          value: redis-svc
        - name: C_FORCE_ROOT
          value: "true"
        - name: PYTHONUNBUFFERED
          value: "1"
        ports:
        - containerPort: 8080
        command:
          - celery
        args:
          - "-A"
          - "app.celery"
          - "worker"
          - "--loglevel=info"
#        volumeMounts:
#        - name: webapp-persistent-storage
#          mountPath: /tmp
#      volumes:
#      - name: webapp-persistent-storage
#        persistentVolumeClaim:
#          claimName: wa-pvc

