apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  labels:
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: celery
      tier: backend
  template:
    metadata:
      labels:
        app: celery
        tier: backend
    spec:
      containers:
      - image: aterhune1984/webappv2:_8d3c026cae408a1df71c2af61344d943ee12b0ab
        name: celery
        resources:
          requests:
            cpu: 0.2
        env:
        - name: REDIS_HOST
          value: redis-svc
        - name: C_FORCE_ROOT
          value: "true"
        - name: PYTHONUNBUFFERED
          value: "1"
        ports:
        - containerPort: 8080
        command:
          - celery
        args:
          - "-A"
          - "app.celery"
          - "worker"
          - "--loglevel=info"
        volumeMounts:
        - name: webapp-persistent-storage
          mountPath: /hello
      volumes:
      - name: webapp-persistent-storage
        persistentVolumeClaim:
          claimName: wa-pvc

