apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prov-dash-configmap
data:
  default.yaml: |
    apiVersion: 1
    providers:
    - name: 'Metrics'
      updateIntervalSeconds: 10
      allowUiUpdates: true
      type: file
      options:
        path: /var/lib/grafana/dashboards
        foldersFromFilesStructure: true
    
