apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    scrape_configs:
      - job_name: 'myflaskapp'
        static_configs:
          - targets: ['webapp:8080']
