apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'myflaskapp'
        static_configs:
          - targets: ['webapp-svc:80']
