name: Deploy to Amazon ECS and cleanup

on:
  push:
    branches:
      - 'ENV-*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_USER }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_KEY }}
      AWS_REGION: us-west-2

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_IMAGE }}
        build-args: |
          APP_NAME=my-app
          APP_PORT=5000

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push Docker image to Amazon ECR
      run: |
        docker tag ${{ secrets.DOCKER_IMAGE }} ${{ secrets.DOCKER_IMAGE }}:latest
        docker push ${{ secrets.DOCKER_IMAGE }}:latest

    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy@v1
      with:
        cluster: ${{ secrets.ECS_CLUSTER_NAME }}
        service: ${{ secrets.ECS_SERVICE_NAME }}
        image: ${{ secrets.DOCKER_IMAGE }}:latest
        container-name: ${{ secrets.CONTAINER_NAME }}
        container-port: 5000

    - name: Save logs to CloudWatch Logs
      run: |
        aws logs create-log-group --log-group-name my-app-logs
        aws ecs describe-tasks --cluster ${{ secrets.ECS_CLUSTER_NAME }} --tasks "$(aws ecs list-tasks --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service-name ${{ secrets.ECS_SERVICE_NAME }} --desired-status RUNNING --output text | cut -f 2)" --output json | jq -r '.tasks[].containers[].taskArn' | xargs -I {} aws logs create-log-stream --log-group-name my-app-logs --log-stream-name {}

    - name: Wait for 48 hours
      run: sleep 172800

    - name: Teardown application
      run: |
        aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service ${{ secrets.ECS_SERVICE_NAME }} --desired-count 0
        aws ecs delete-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service ${{ secrets.ECS_SERVICE_NAME }}