name: Build and Push Docker Image

on:
  push:
    paths:
      - "Dockerfile"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_USER }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.login-ecr.outputs.registry }}/<your-repo-name>:latest

      - name: Push Docker image to Amazon ECR
        if: steps.build-image.outputs.digest != ''
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.build-image.outputs.digest }}
        run: |
          docker tag ${{ steps.build-image.outputs.image }} $ECR_REGISTRY/<your-repo-name>:$IMAGE_TAG
          docker push $ECR_REGISTRY/<your-repo-name>:$IMAGE_TAG
