name: "push to kubernetes"

# any time you modify k8s directory files, this updates and pushes
on:
  pull_request:
    types: [opened]
    branches:
      - STAGING
    paths:
      - 'k8s/**'

env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_USER }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_KEY }}
 # S3 bucket for the Terraform state
 BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}


jobs:

  kubernetes:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Generate kubeconfig
        run: |
          export CLUSTER_NAME=$(/usr/local/bin/aws eks --region us-east-2 list-clusters --output text --query 'clusters[0]')
          echo $CLUSTER_NAME
          /usr/local/bin/aws eks --region us-east-2 update-kubeconfig --name $CLUSTER_NAME

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s
