name: Staging Terraform Workflow

on:
  pull_request:
    types: [opened,closed]
    branches:
      - STAGING
    paths:
      - terraform/**


env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_USER }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_KEY }}
 # S3 bucket for the Terraform state
 BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}


jobs:
  build-terraform:
    name: "Terraform Infrastructure Build"

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v3

      # This step sets up the Terraform environment
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4

      # This step initializes the Terraform working directory
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Terraform validate
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        id: validate
        run: terraform validate


      - name: Terraform plan
        id: plan
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: terraform plan -no-color -input=false -out=tfplan
        continue-on-error: true



      #- name: Do Unit Tests
      #  id: unit
      #  if: github.event_name == 'pull_request' && github.event.action == 'opened' && github.base_ref == 'STAGING'
      #  run: echo "Hello World"


      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      # This step applies the Terraform configuration to the staging environment
      - name: Terraform apply staging
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        env:
          TF_VAR_environment: STAGING
        run: |
          terraform apply -auto-approve "tfplan"
          echo "::set-output name=apply-successful::true"

      #- name: Do Integration Tests
      #  if: github.event_name == 'pull_request' && github.event.action == 'opened' && github.base_ref == 'STAGING'
      #  run: echo "Hello another World"


      # This step destroys the Terraform environment upon closing a pull request against the staging branch
      - name: Terraform destroy staging
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        env:
          TF_VAR_environment: STAGING
        run: |
            terraform destroy -auto-approve
